name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Run Docker container
        run: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker run -d --name my-python-app -p 8000:8000 my-python-app